/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { ConfidentialPayrollToken__factory } from "./ConfidentialPayrollToken__factory";
export { Payroll__factory } from "./Payroll__factory";
export { PayrollFactory__factory } from "./PayrollFactory__factory";
