/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayrollFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allEmployers"
      | "confidentialToken"
      | "employerPayroll"
      | "getAllEmployers"
      | "getPayroll"
      | "registerEmployer"
      | "totalEmployers"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PayrollCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "allEmployers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "employerPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEmployers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPayroll",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerEmployer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEmployers",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allEmployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "employerPayroll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEmployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayroll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerEmployer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEmployers",
    data: BytesLike
  ): Result;
}

export namespace PayrollCreatedEvent {
  export type InputTuple = [employer: AddressLike, payroll: AddressLike];
  export type OutputTuple = [employer: string, payroll: string];
  export interface OutputObject {
    employer: string;
    payroll: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PayrollFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PayrollFactory;
  waitForDeployment(): Promise<this>;

  interface: PayrollFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allEmployers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  confidentialToken: TypedContractMethod<[], [string], "view">;

  employerPayroll: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getAllEmployers: TypedContractMethod<[], [string[]], "view">;

  getPayroll: TypedContractMethod<[employer: AddressLike], [string], "view">;

  registerEmployer: TypedContractMethod<[], [string], "nonpayable">;

  totalEmployers: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allEmployers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "employerPayroll"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAllEmployers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPayroll"
  ): TypedContractMethod<[employer: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "registerEmployer"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "totalEmployers"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PayrollCreated"
  ): TypedContractEvent<
    PayrollCreatedEvent.InputTuple,
    PayrollCreatedEvent.OutputTuple,
    PayrollCreatedEvent.OutputObject
  >;

  filters: {
    "PayrollCreated(address,address)": TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;
    PayrollCreated: TypedContractEvent<
      PayrollCreatedEvent.InputTuple,
      PayrollCreatedEvent.OutputTuple,
      PayrollCreatedEvent.OutputObject
    >;
  };
}
