/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PayrollInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchOnboardEmployees"
      | "batchPaySalaries"
      | "confidentialProtocolId"
      | "confidentialToken"
      | "editEmployee"
      | "employer"
      | "getSalaryHistoryLength"
      | "onboardEmployee"
      | "paySalary"
      | "removeEmployee"
      | "whitelisted"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmployeeOnboarded"
      | "EmployeeRemoved"
      | "EmployeeUpdated"
      | "SalaryPaid"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchOnboardEmployees",
    values: [AddressLike[], BytesLike[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchPaySalaries",
    values: [AddressLike[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "editEmployee",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "employer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSalaryHistoryLength",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onboardEmployee",
    values: [AddressLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paySalary",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeEmployee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelisted",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchOnboardEmployees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchPaySalaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "employer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSalaryHistoryLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onboardEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paySalary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeEmployee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelisted",
    data: BytesLike
  ): Result;
}

export namespace EmployeeOnboardedEvent {
  export type InputTuple = [
    employer: AddressLike,
    employee: AddressLike,
    encryptedSalary: BytesLike,
    inputProof: BytesLike,
    signature: BytesLike
  ];
  export type OutputTuple = [
    employer: string,
    employee: string,
    encryptedSalary: string,
    inputProof: string,
    signature: string
  ];
  export interface OutputObject {
    employer: string;
    employee: string;
    encryptedSalary: string;
    inputProof: string;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeRemovedEvent {
  export type InputTuple = [employee: AddressLike];
  export type OutputTuple = [employee: string];
  export interface OutputObject {
    employee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmployeeUpdatedEvent {
  export type InputTuple = [
    employer: AddressLike,
    employee: AddressLike,
    newEncryptedSalary: BytesLike,
    newInputProof: BytesLike,
    newSignature: BytesLike,
    timestamp: BigNumberish,
    salaryId: BytesLike,
    payroll: AddressLike
  ];
  export type OutputTuple = [
    employer: string,
    employee: string,
    newEncryptedSalary: string,
    newInputProof: string,
    newSignature: string,
    timestamp: bigint,
    salaryId: string,
    payroll: string
  ];
  export interface OutputObject {
    employer: string;
    employee: string;
    newEncryptedSalary: string;
    newInputProof: string;
    newSignature: string;
    timestamp: bigint;
    salaryId: string;
    payroll: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SalaryPaidEvent {
  export type InputTuple = [
    employer: AddressLike,
    employee: AddressLike,
    index: BigNumberish,
    salary: BytesLike,
    timestamp: BigNumberish,
    paymentId: BytesLike,
    payroll: AddressLike
  ];
  export type OutputTuple = [
    employer: string,
    employee: string,
    index: bigint,
    salary: string,
    timestamp: bigint,
    paymentId: string,
    payroll: string
  ];
  export interface OutputObject {
    employer: string;
    employee: string;
    index: bigint;
    salary: string;
    timestamp: bigint;
    paymentId: string;
    payroll: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Payroll extends BaseContract {
  connect(runner?: ContractRunner | null): Payroll;
  waitForDeployment(): Promise<this>;

  interface: PayrollInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchOnboardEmployees: TypedContractMethod<
    [
      employees: AddressLike[],
      encryptedSalaries: BytesLike[],
      inputProofs: BytesLike[],
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  batchPaySalaries: TypedContractMethod<
    [
      employees: AddressLike[],
      encryptedSalaries: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  confidentialToken: TypedContractMethod<[], [string], "view">;

  editEmployee: TypedContractMethod<
    [
      employee: AddressLike,
      newEncryptedSalary: BytesLike,
      newInputProof: BytesLike,
      newSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  employer: TypedContractMethod<[], [string], "view">;

  getSalaryHistoryLength: TypedContractMethod<
    [employee: AddressLike],
    [bigint],
    "view"
  >;

  onboardEmployee: TypedContractMethod<
    [
      employee: AddressLike,
      encryptedSalary: BytesLike,
      inputProof: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  paySalary: TypedContractMethod<
    [employee: AddressLike, salaryEncrypted: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  removeEmployee: TypedContractMethod<
    [employee: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelisted: TypedContractMethod<[employee: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchOnboardEmployees"
  ): TypedContractMethod<
    [
      employees: AddressLike[],
      encryptedSalaries: BytesLike[],
      inputProofs: BytesLike[],
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchPaySalaries"
  ): TypedContractMethod<
    [
      employees: AddressLike[],
      encryptedSalaries: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "editEmployee"
  ): TypedContractMethod<
    [
      employee: AddressLike,
      newEncryptedSalary: BytesLike,
      newInputProof: BytesLike,
      newSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "employer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSalaryHistoryLength"
  ): TypedContractMethod<[employee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "onboardEmployee"
  ): TypedContractMethod<
    [
      employee: AddressLike,
      encryptedSalary: BytesLike,
      inputProof: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "paySalary"
  ): TypedContractMethod<
    [employee: AddressLike, salaryEncrypted: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeEmployee"
  ): TypedContractMethod<[employee: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelisted"
  ): TypedContractMethod<[employee: AddressLike], [boolean], "view">;

  getEvent(
    key: "EmployeeOnboarded"
  ): TypedContractEvent<
    EmployeeOnboardedEvent.InputTuple,
    EmployeeOnboardedEvent.OutputTuple,
    EmployeeOnboardedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeRemoved"
  ): TypedContractEvent<
    EmployeeRemovedEvent.InputTuple,
    EmployeeRemovedEvent.OutputTuple,
    EmployeeRemovedEvent.OutputObject
  >;
  getEvent(
    key: "EmployeeUpdated"
  ): TypedContractEvent<
    EmployeeUpdatedEvent.InputTuple,
    EmployeeUpdatedEvent.OutputTuple,
    EmployeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SalaryPaid"
  ): TypedContractEvent<
    SalaryPaidEvent.InputTuple,
    SalaryPaidEvent.OutputTuple,
    SalaryPaidEvent.OutputObject
  >;

  filters: {
    "EmployeeOnboarded(address,address,bytes32,bytes,bytes)": TypedContractEvent<
      EmployeeOnboardedEvent.InputTuple,
      EmployeeOnboardedEvent.OutputTuple,
      EmployeeOnboardedEvent.OutputObject
    >;
    EmployeeOnboarded: TypedContractEvent<
      EmployeeOnboardedEvent.InputTuple,
      EmployeeOnboardedEvent.OutputTuple,
      EmployeeOnboardedEvent.OutputObject
    >;

    "EmployeeRemoved(address)": TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;
    EmployeeRemoved: TypedContractEvent<
      EmployeeRemovedEvent.InputTuple,
      EmployeeRemovedEvent.OutputTuple,
      EmployeeRemovedEvent.OutputObject
    >;

    "EmployeeUpdated(address,address,bytes32,bytes,bytes,uint256,bytes32,address)": TypedContractEvent<
      EmployeeUpdatedEvent.InputTuple,
      EmployeeUpdatedEvent.OutputTuple,
      EmployeeUpdatedEvent.OutputObject
    >;
    EmployeeUpdated: TypedContractEvent<
      EmployeeUpdatedEvent.InputTuple,
      EmployeeUpdatedEvent.OutputTuple,
      EmployeeUpdatedEvent.OutputObject
    >;

    "SalaryPaid(address,address,uint256,bytes32,uint256,bytes32,address)": TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;
    SalaryPaid: TypedContractEvent<
      SalaryPaidEvent.InputTuple,
      SalaryPaidEvent.OutputTuple,
      SalaryPaidEvent.OutputObject
    >;
  };
}
